services:
  nexads:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexads
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./proxy.txt:/app/proxy.txt:ro
      - ./referrers.json:/app/referrers.json:ro
      - ./profiles:/app/profiles
